# Generated by Django 4.2.1 on 2024-03-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
