# Generated by Django 4.2.11 on 2024-03-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_article',
            field=models.IntegerField(choices=[(1, 'Article'), (0, 'Event')], default=0),
        ),
    ]
